eureka:
  client:
    serviceUrl:
        defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost

microservice:
    payment:
        endpoints:
            endpoint:
                uri: http://PAYMENT/payment/doPayment
    order:
        endpoints:
            endpoint:
                uri: http://ORDER/order/bookOrder
